spring.application.name=ClinicApp
 
# Server port configuration
server.port=8081

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/clinic
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=

# JPA / Hibernate: NO recrear las tablas, usar las existentes
# 'update' → actualiza schema si hay cambios en entidades
# 'validate' → solo valida sin cambiar nada
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect